# Generated by Django 4.2 on 2026-05-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ['-rank', '-created_at']},
        ),
        migrations.AddField(
            model_name='searchresult',
            name='rank',
            field=models.FloatField(default=0.0, help_text='Static importance score'),
        ),
    ]
